Repository ooni/probe-cli, pull requests merged in 2019-10, with the labels that each got.

#53 Implement the show command
  .travis.yml
  config/settings.go
  go.mod
  go.sum
  internal/cli/run/run.go
  internal/cli/show/show.go
  internal/database/actions.go
  internal/log/handlers/cli/cli.go
  internal/log/handlers/cli/measurements.go
  internal/output/output.go
  internal/util/util.go
  nettests/websites/web_connectivity.go
  scripts/travis_test.sh
  testdata/testing-config.json
Labels: P0

#58 Rename the binary as ooniprobe
  build.sh
  cmd/ooniprobe/main.go
  scripts/travis_test.sh
Labels: P0, refactoring

#60 Upgrade to ooni/probe-engine@v0.1.1
  go.mod
  go.sum
  internal/cli/root/root.go
  internal/cli/run/run.go
  internal/database/actions.go
  internal/database/actions_test.go
  internal/enginex/enginex.go
  internal/util/util.go
Labels: P0, enhancement

#61 Make sure `ooniprobe show <id>` is WAI
  internal/cli/list/list.go
  internal/cli/show/show.go
  internal/database/actions.go
  internal/util/util.go
Labels: P0, bug

#62 Publish code used to generate v3.0.0-beta.4
  .goreleaser.yml
  Makefile
  build.sh
Labels: P0, enhancement, please preserve history

#65 build.sh: produce same release as before
  build.sh
Labels: P0, bug, please preserve history
